// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR60O18qJdkDz4Mz457w12PdrGE73tFis',
    appId: '1:185796974935:web:a9079c8c39da119b7a0612',
    messagingSenderId: '185796974935',
    projectId: 'sampark-chat-app-e4ef5',
    authDomain: 'sampark-chat-app-e4ef5.firebaseapp.com',
    storageBucket: 'sampark-chat-app-e4ef5.appspot.com',
    measurementId: 'G-8RXRYX40H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpz-bU-BVDbCrgKdnnp19hGQ3aOeSZ-Vk',
    appId: '1:185796974935:android:16c628ea350411bc7a0612',
    messagingSenderId: '185796974935',
    projectId: 'sampark-chat-app-e4ef5',
    storageBucket: 'sampark-chat-app-e4ef5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR60O18qJdkDz4Mz457w12PdrGE73tFis',
    appId: '1:185796974935:web:229f67e10d7defe47a0612',
    messagingSenderId: '185796974935',
    projectId: 'sampark-chat-app-e4ef5',
    authDomain: 'sampark-chat-app-e4ef5.firebaseapp.com',
    storageBucket: 'sampark-chat-app-e4ef5.appspot.com',
    measurementId: 'G-0T3Z1648FF',
  );
}
